[package]
name = "koopman_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ode_solvers =   "0.3.6"
rand_distr  =   "0.4.3"
rand        =   "0.8.5"